apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: messenger-auth
  labels:
    app: messenger
    component: auth
spec:
  selector:
    app: messenger
    component: auth
  ports:
  - name: http
    port: 8083
    targetPort: 80
    protocol: TCP
  type: ClusterIP
