apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: messenger-chat
  labels:
    app: messenger
    component: chat
spec:
  selector:
    app: messenger
    component: chat
  ports:
  - name: http
    port: 8084
    targetPort: 80
    protocol: TCP
  type: ClusterIP
