apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: messenger-database
  labels:
    app: messenger
    component: database
spec:
  selector:
    app: messenger
    component: database
  ports:
  - name: http
    port: 8085
    targetPort: 80
    protocol: TCP
  type: ClusterIP
