apiVersion: v1
kind: Service
metadata:
  name: messaging-service
  namespace: messenger-messaging
  labels:
    app: messenger
    component: messaging
spec:
  selector:
    app: messenger
    component: messaging
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
  type: ClusterIP
