apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: messenger-frontend
  labels:
    app: messenger
    component: frontend
spec:
  selector:
    app: messenger
    component: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
